### ISSUE TITLE
Addon doesn't show up!

### ISSUE THREAD

**Issue by thegreatsai** [x6ud/controlnet-render-blender-addon#1]
I installed the addon on Blender 3.6. It doesn't show up on addon window. At the time, I didn't have Stable Diffusion running. So, that could be the issue why it's not showing? Also tried on 3.5 and same thing. It's a no show! I will try tonight with Stable Diffusion on to see if it pops up.

**Comment by x6ud** [comment]
In edit -> preferences -> addons, remember to check the addon after installing
And it only shows in the "rendering" workspace side panel
